### ISSUE TITLE
Request: Possible to support Flexit Bodo Supreme fan?

### ISSUE THREAD

**Issue by kristianwh** [aglehmann/pyEcovent#20]
Hi, I have bought a new Flexit Bodo Supreme fan, and wondered if this would be possible to support with this library.
https://p.flexit.no/en/products/bathroom_fan/bathroom-fan-bodo/bathroom-fan-bodo-supreme-white/
I sniffed a bit of traffic from the app (Flexit Fans), and it connects to some blauberg cloud service.
It also looks like it listens on UDP port 4000:
Nmap scan report for 192.168.10.98
Host is up (0.064s latency).

PORT     STATE         SERVICE
4000/udp open|filtered icq

Close this if this is not relevant for this library, or kindly kick me in the right direction.
All I want is the ablity to trigger the boost function from home assistant ;)

**Comment by kristianwh** [comment]
Update: I added 
0xD00: 'Flexit Bodo Supreme' 
to unit_types, and then got a nice printout of the statuses when trying the test.py from the project.

python3 test.py
['192.168.10.98']
192.168.10.98
state: None
speed: None
boost_status: None
timer_mode: None
timer_counter: 0h 0m 0s 
humidity_sensor_state: on
relay_sensor_state: None
analogV_sensor_state: None
humidity_treshold: None
battery_voltage: 3036 mV
humidity: 43
analogV: None
relay_status: None
man_speed: None
fan1_speed: None
fan2_speed: 540
filter_timer_countdown: None
boost_time: None
rtc_time: 11h 49m 50s 
rtc_date: None
weekly_schedule_state: None
weekly_schedule_setup: None
device_search: 003F001D46465716
device_password: 1111
machine_hours: None
alarm_status: None
cloud_server_state: None
firmware: 0.1 2022-10-04
filter_replacement_status: None
wifi_operation_mode: None
wifi_name: xxx
wifi_pasword: yyy
wifi_enc_type: wpa_wpa2_psk
wifi_freq_chnnel: 11
wifi_dhcp: DHCP
wifi_assigned_ip: 192.168.4.1
wifi_assigned_netmask: 255.255.255.0
wifi_main_gateway: 192.168.0.1
curent_wifi_ip: 192.168.10.98
airflow: None
analogV_treshold: None
unit_type: Flexit Bodo Supreme
night_mode_timer: None
party_mode_timer: None
humidity_status: off
Traceback (most recent call last):
  File "/home/krizze/src/pyEcovent/test.py", line 22, in <module>
    attr = str(getattr(fan , fan.params[i][0]))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krizze/src/pyEcovent/ecoventv2/__init__.py", line 919, in analogV_status
    return self._analogV_status
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Fan' object has no attribute '_analogV_status'. Did you mean: 'analogV_status'?
